//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentingSystem.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentInfoes
    {
        public int Id { get; set; }
        public bool ReqPending { get; set; }
        public System.DateTime BeginningOfRenting { get; set; }
        public System.DateTime EndingOfRenting { get; set; }
        public int VehicleId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
