//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentingSystem.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentInfos
    {
        public int Id { get; set; }
        public Nullable<bool> IsRequestPending { get; set; }
        public Nullable<System.DateTime> DatetimeOfRequest { get; set; }
        public Nullable<bool> IsRented { get; set; }
        public Nullable<System.DateTime> BeginningOfRenting { get; set; }
        public Nullable<System.DateTime> EndingOfRenting { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> StaffThatConfirmsOrRejects { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Staffs Staffs { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
