//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentingSystem.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staffs()
        {
            this.RentInfos = new HashSet<RentInfos>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PhotoURL { get; set; }
        public string CityOfBirth { get; set; }
        public Nullable<long> IdentificationNumber { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BeginningDateOfDriverLicense { get; set; }
        public Nullable<System.DateTime> EndingDateOfDriverLicense { get; set; }
        public Nullable<System.DateTime> DatetimeOfCreated { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Managers Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentInfos> RentInfos { get; set; }
    }
}
