//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentingSystem.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.RentInfos = new HashSet<RentInfos>();
        }
    
        public int Id { get; set; }
        public string Brand { get; set; }
        public string ModelName { get; set; }
        public string Plate { get; set; }
        public Nullable<int> MinimumAgeLimit { get; set; }
        public string PhotoURL { get; set; }
        public Nullable<int> RequiredOldForLicense { get; set; }
        public Nullable<int> CurrentKm { get; set; }
        public Nullable<bool> HaveAirBag { get; set; }
        public Nullable<int> AmoutOfSeat { get; set; }
        public Nullable<int> VolumeOfLuggage { get; set; }
        public Nullable<System.DateTime> DatetimeOfCreated { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DailyPrice { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentInfos> RentInfos { get; set; }
    }
}
