//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentingSystem.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.RentInfoes = new HashSet<RentInfoes>();
        }
    
        public int Id { get; set; }
        public string Brand { get; set; }
        public string ModelName { get; set; }
        public string Plate { get; set; }
        public byte RequiredOldForLicence { get; set; }
        public byte MinimumAgeLimit { get; set; }
        public bool HaveAirbag { get; set; }
        public byte VolumeOfLuggage { get; set; }
        public byte AmountOfSeat { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentInfoes> RentInfoes { get; set; }
    }
}
